// Global using directives

global using System;
global using System.Collections.Generic;
global using System.IO.Compression;
global using System.Linq;
global using System.Threading.Tasks;
global using Lion.AbpPro.BasicManagement;
global using Lion.AbpPro.NotificationManagement;
global using Lion.AbpSuite.DataTypes;
global using Lion.AbpSuite.DataTypes.Dto;
global using Lion.AbpSuite.EntityModels;
global using Lion.AbpSuite.EntityModels.Dto;
global using Lion.AbpSuite.EnumTypes;
global using Lion.AbpSuite.EnumTypes.Dto;
global using Lion.AbpSuite.Extensions;
global using Lion.AbpSuite.Files;
global using Lion.AbpSuite.Generators.Dto;
global using Lion.AbpSuite.Localization;
global using Lion.AbpSuite.Permissions;
global using Lion.AbpSuite.Projects;
global using Lion.AbpSuite.Projects.Dto;
global using Lion.AbpSuite.Projects.Dto.Generators;
global using Lion.AbpSuite.Templates;
global using Lion.AbpSuite.Templates.Dto;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.Extensions.Configuration;
global using Newtonsoft.Json;
global using Volo.Abp;
global using Volo.Abp.Application.Dtos;
global using Volo.Abp.Application.Services;
global using Volo.Abp.AutoMapper;
global using Volo.Abp.BackgroundJobs.Hangfire;
global using Volo.Abp.DependencyInjection;
global using Volo.Abp.Modularity;
global using Profile = AutoMapper.Profile;